### Site Settings ###
title               : Daniel Costa
description         :                                # >- means to ignore newlines until "url:"
                      Welcome to my Tech-Blog,<br/>
                      I am a Father/Geek! A guy that loves technology! I try to automate everything!<br/>
                      In this blog you will find articles about DevOps, Development, IT, and Home Automation!

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : daco-tech/daco-tech.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Daniel Costa
  image             : https://avatars1.githubusercontent.com/u/11052797?s=460&v=4
# behance           : daco-tech
# dribbble          : your_username
  email             : blog@danielcosta.pt
  facebook          : danieljcosta
  github            : daco-tech
# gitlab            : your_username
# instagram         : your_username
  linkedin          : danieljcosta
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : DanielJCosta
# vimeo             : your_username
# youtube           : your_channel_name

### Pagination ###
#paginate: 6
#paginate_path: "/articles/page-:num/"


### Posts Permalink ###
#permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

